[accessibility]
ui_scale = 1.2

[bar.default]
border = "on_primary"
center = [ "group:g2" ]
concave_edge_corners = true
end = [ "tray", "group:g1", "group:g3", "session" ]
font_scale = 0.89999998733401299
font_weight = 400
margin_edge = 0
margin_ends = 400
padding = 6
radius_bottom_left = 12
radius_bottom_right = 12
radius_top_left = 12
radius_top_right = 12
scale = 1.1000000000000001
start = [ "control-center", "workspaces", "audio_visualizer" ]
thickness = 40
widget_spacing = 8

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "temp", "sysmon_2", "sysmon_3" ]
    opacity = 0.60000002384185791
    padding = 8.0
    radius = 8.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "surface_variant"
    foreground = "secondary"
    id = "g3"
    members = [ "media", "volume", "clipboard", "bluetooth", "network", "battery", "privacy" ]
    opacity = 0.69999998807907104
    padding = 8.0
    radius = 8.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "weather", "clock" ]
    opacity = 0.69999998807907104
    padding = 12.0
    radius = 8.0
    widget_spacing = 12

[battery]
warning_threshold = 20

    [battery.device."/org/freedesktop/UPower/devices/headphones_dev_20_FA_85_90_B4_84"]
    warning_threshold = 10

[hot_corners.top_left]
action = "command"

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "HDMI-A-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.69999998435378075
max_visible = 3
offset_x = 24
offset_y = 24

[osd]
background_opacity = 0.69999998435378075
offset_y = 80
position = "bottom_center"
position_vertical = "bottom_center"

[plugins]
enabled = [ "thepunkoff/pomodoro", "noctalia/timer" ]

[shell]
clipboard_image_action_command = "swash --stdin --name \"swash-$(date +'%Y-%m-%d_%H:%M:%S').png\""
font_family = "JetBrainsMono NF"
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true

    [shell.greeter_sync]
    auto_sync = false

    [shell.launcher]
    compact = true

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_control_center = true
    polkit_placement = "attached"
    session_placement = "attached"
    session_position = "center"
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    copy_to_clipboard = false
    pipe_command = "swash --stdin --name \"swash-$(date +'%Y-%m-%d_%H:%M:%S').png\""
    pipe_to_command = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "4"
    variant = "destructive"

[system.monitor]
gpu_poll_seconds = 2

[theme]
builtin = "Gruvbox"
community_palette = "Gruvbox Material Hard"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "qt" ]
    community_ids = [ "pywalfox-beta4", "discord", "neovim" ]

[wallpaper]
directory = "/home/coby/Wallpapers"

    [wallpaper.default]
    path = "/home/coby/Wallpapers/Gruvbox/Clay Banks.jpg"

    [wallpaper.last]
    path = "/home/coby/Wallpapers/Gruvbox/Clay Banks.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/coby/Wallpapers/Gruvbox/Clay Banks.jpg"

[weather]
refresh_minutes = 15
unit = "imperial"

[widget.audio_visualizer]
bands = 128
color_2 = "secondary"
width = 129

[widget.battery]
hide_when_full = true

[widget.clipboard]
glyph = "clipboard-list"

[widget.clock]
anchor = true
color = "secondary"
format = "{:%I:%M %p}"
tooltip_format = "{:%I:%M %p on %D}"

    [widget.clock.actions]
    right = "panel-toggle control-center home"

[widget.control-center]
capsule = true
capsule_opacity = 0.70000000000000007
capsule_radius = 8
color = "primary"
glyph = "grid-dots"

[widget.launcher]
capsule = true
capsule_fill = "surface_variant"
capsule_opacity = 0.70000000000000007
capsule_padding = 8
capsule_radius = 8
color = "primary"
scale = 0.90000000000000002

[widget.media]
album_art_only = true
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
color = "secondary"
show_label = false

[widget.notifications]
color = "secondary"

[widget.privacy]
hide_inactive = true

[widget.session]
capsule = true
capsule_fill = "surface_variant"
capsule_opacity = 0.70000000000000007
capsule_padding = 8
capsule_radius = 8
color = "error"
scale = 0.90000000000000002

[widget.settings]
enabled = false

[widget.spacer_1]
type = "spacer"

[widget.sysmon_2]
glyph = "gpu-usage"
highlight_color = "primary"
show_value = false
stat = "gpu_temp"
type = "sysmon"

[widget.sysmon_3]
glyph = "cpu-2"
highlight_color = "primary"
stat = "ram_used"
type = "sysmon"

[widget.temp]
glyph = "cpu"
highlight_color = "primary"
show_value = false

[widget.tray]
capsule = true
capsule_fill = "surface_variant"
capsule_opacity = 0.59999999999999998
capsule_radius = 8
drawer = true
icon_color = "secondary"

[widget.volume]
color = "secondary"

[widget.weather]
color = "secondary"
scale = 0.90000000000000002
show_condition = false
show_temperature = false

[widget.workspaces]
active_pill_size = 2.5
capsule = true
capsule_fill = "surface_variant"
capsule_opacity = 0.70000000000000007
capsule_padding = 8
capsule_radius = 8
inactive_pill_size = 1.0
pill_scale = 0.70000000000000007
show_labels = false
