color0 #474747
color1 #ffb4ab
color2 #93d787
color3 #baccb2
color4 #a0cfd3
color5 #93d787
color6 #baccb2
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #93d787
color11 #baccb2
color12 #a0cfd3
color13 #93d787
color14 #baccb2
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #93d787
inactive_border_color #474747
url_color             #93d787

active_tab_foreground   #003a05
active_tab_background   #93d787
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
